namespace DTL.DTO
{
    public static class OrderSheetFields
    {
        public const string PotentialCustomer_AccountNo = "Potentialcustomer_AccountNo";
        public const string PotentialCustomer_AccountName = "Potentialcustomer_AccountName";
        public const string PotentialCustomer_CVR = "Potentialcustomer_CVR";
        public const string AssociatedCompany1_Accountno16 = "Associatedcompany1_Accountno16";
        public const string AssociatedCompany1_AccountName = "Associatedcompany1_AccountName";
        public const string AssociatedCompany1_CVR= "Associatedcompany1_CVR";
        public const string AssociatedCompany2_Accountno16 = "Associatedcompany2_Accountno16";
        public const string AssociatedCompany2_AccountName = "Associatedcompany2_AccountName";
        public const string AssociatedCompany2_CVR= "Associatedcompany2_CVR";
        public const string AssociatedCompany3_AccountName = "Associatedcompany3_AccountName";
        public const string AssociatedCompany3_Accountno16 = "Associatedcompany3_Accountno16";
        public const string AssociatedCompany3_CVR= "Associatedcompany3_CVR";
        public const string AssociatedCompany4_Accountno16 = "Associatedcompany4_Accountno16";
        public const string AssociatedCompany4_AccountName = "Associatedcompany4_AccountName";
        public const string AssociatedCompany4_CVR = "Associatedcompany4_CVR";
        public const string AssociatedCompany5_Accountno16 = "Associatedcompany5_Accountno16";
        public const string AssociatedCompany5_AccountName = "Associatedcompany5_AccountName";
        public const string AssociatedCompany5_CVR = "Associatedcompany5_CVR";
        public const string AssociatedCompany6_Accountno16 = "Associatedcompany6_Accountno16";
        public const string AssociatedCompany6_AccountName = "Associatedcompany6_AccountName";
        public const string AssociatedCompany6_CVR = "Associatedcompany6_CVR";
        public const string AssociatedCompany7_Accountno16 = "Associatedcompany7_Accountno16";
        public const string AssociatedCompany7_AccountName = "Associatedcompany7_AccountName";
        public const string AssociatedCompany7_CVR = "Associatedcompany7_CVR";
        public const string AssociatedCompany8_Accountno16 = "Associatedcompany8_Accountno16";
        public const string AssociatedCompany8_AccountName = "Associatedcompany8_AccountName";
        public const string AssociatedCompany8_CVR = "Associatedcompany8_CVR";
        public const string AssociatedCompany9_Accountno16 = "Associatedcompany9_Accountno16";
        public const string AssociatedCompany9_AccountName = "Associatedcompany9_AccountName";
        public const string AssociatedCompany9_CVR = "Associatedcompany9_CVR";
        public const string AssociatedCompany10_Accountno16= "Associatedcompany10_Accountno16";
        public const string AssociatedCompany10_AccountName= "Associatedcompany10_AccountName";
        public const string AssociatedCompany10_CVR = "Associatedcompany10_CVR";
        public const string PotentialCustomerServiceChannel= "Potentialcustomer_ServiceChannel";
        public const string NumberOfCPR = "NumberOfCPR";
        public const string AverageContribution = "Averagecontribution";
        public const string StartingDateExpected = "StartingDateExpected";
        public const string PensionProviderChange = "PensionProviderChange";
        public const string PensionProviderChangeDate = "PensionProviderChangeDate";
        public const string PensionCompany = "PensionCompany";
        public const string Entering = "Entering";
        public const string EmployeesWithAMP = "EmployeeswithAMP";
        public const string AMPForStudents = "AMPforStudents";
        public const string AMPNo1 = "AMPno1";
        public const string Expire = "Expire";
        public const string HealthInsuranceEntering = "HealthInsuranceEntering";
        public const string HealthInsuranceSupplier = "HealthInsuranceSupplier";
        public const string DisabilityPension = "DisabilityPension";
        public const string DisabilityLumpSum = "DisabilityLumpsum";
        public const string CriticalIllness = "CriticalIllness";
        public const string CoverageByDeathPercentage = "CoverageByDeathPercentage";
        public const string ChildrensCoverageByDeathPercentage= "ChilderensCoverageByDeathPercentage"; 
        public const string CriticalIllnessForChildren = "CriticalIllnessForChildren";
        public const string ExpireChildrensCoverage = "ExpireChildrensCoverage";
        public const string ResulterendeErhvervsklasse = "ResulterendeErhvervsklasse";
        public const string IndtradelsesAlder = "Indtradelsesalder";
        public const string ReguleringsDato = "Reguleringsdato";
        public const string IsHealthInsuranceIncluded = "IsHealthInsuranceIncluded";
        public const string Topic = "Topic";
        public const string HoldersAreReportedAsPrivate = "HoldersAreReportedAsPrivate";
        public const string PayoutToEmployer = "PayoutToEmployer";
        public const string DegreeOfCompensation = "DegreeOfCompensation";
        public const string ExpireCriticalIllnessForChildren = "ExpireCriticalIllnessForChildren";
    }
}